# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
permissions:
  contents: read

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

env:
  GOLANG_PROTOBUF_REGISTRATION_CONFLICT: warn

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./parser
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24

      - name: Build
        env:
          GOOS: js
          GOARCH: wasm
        run: go build -ldflags="-s -w" -v ./wasm.go

      - name: Test
        run: go test -v ./...
